hierarchy:
  pdist_metric: 'euclidean' # pairwise distance metric
  pdist_args: ~
  linkage_method: 'average' # https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html
permute:
  iters: 1000
  func: 'ecdf' # or ecdf