discretize:
  bypass_if_cont: True # bypass discretization if all features are continuous
  func: ~ # None, 'equal-freq'
  num_bins: ~
hierarchy:
  pdist_metric: 'euclidean' # pairwise distance metric
  linkage_method: 'average' # https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html
permute:
  iters: 10000
  func: 'ecdf' # 'ecdf' or 'gpd'
stats:
  fdr_alpha: 0.05
  fdr_method: 'bh'
  fnr_thresh: 0.1